--- 
pid: tmp/pids/thin.pid
address: 127.0.0.1
port: 5000
timeout: 30
wait: 30
log: log/thin.log
max_conns: 1024
require: []

max_persistent_conns: 512
environment: production
servers: 4
daemonize: true
chdir: /var/www/socialactions/releases/20110907101616
